### ISSUE TITLE
Реализовать експорт в csv.

### ISSUE THREAD

**Issue by p-p-m** [StoreInBox/sib-export#1]
1. Клонировать приложение sib-export: https://github.com/StoreInBox/sib-export
2. Установить develop версию проекта: `python setup.py develop`
3. Посмотреть как сделан экспорт в pdf:
   - зайти на url `/products/export/pdf/?download=1` и проверить что загружается файл
   - просмотреть код
4. Реализовать метод `export.utils.to_csv` так чтобы таблица описаная в шаблоне `/templates/export/product_list.html` переводилась в csv документ.
5. Дописать все что нужно во вью эксопрта чтобы заработал экспорт в csv.

**Comment by awsh10** [comment]
Устанавливать приложение  в sib-main/main

**Comment by p-p-m** [comment]
> Устанавливать приложение  в sib-main/main

нет, в отдельную папку

**Comment by awsh10** [comment]
установил sb-main, запустил админку - работает. Установил sib-export ппп1,2. остановился на п3 -  зайти на url /products/export/pdf/?download=1. Что за урл, на каком проекте  - на sib-main?

**Comment by p-p-m** [comment]
да урл на проекте sib-main

**Comment by p-p-m** [comment]
сделайте git pull на проекте sib-main, перед тем как пробовать url

**Comment by awsh10** [comment]
сделал

Page not found (404)
Request Method:     GET
Request URL:    http://127.0.0.1:8000//products/export/pdf/?download=1

Using the URLconf defined in main.server.urls, Django tried these URL patterns, in this order:

```
^(?P<category_pk>[\d+])/(?P<category_slug>[-\w]+)/$ [name='products']
^$ [name='home']
^products/export/(?P<export_format>pdf)/$ [name='products-export']
^admin/
^media\/(?P<path>.*)$
^static\/(?P<path>.*)$
```

The current URL, /products/export/pdf/, didn't match any of these.

**Comment by p-p-m** [comment]
> http://127.0.0.1:8000//products/export/pdf/?download=1  

2 слеша после 8000

**Comment by awsh10** [comment]
Тысячу извинений 

29 октября 2015, 06:33:19, от "p-p-m" < notifications@github.com >: 

http://127.0.0.1:8000//products/export/pdf/?download=1 2 слеша после 8000 —

**Comment by awsh10** [comment]
Я, наверное, что-то не так понимаю. Ибо слишком все просто. 
csv - Это текстовый формат представления данных таблиц в виде строк, каждая  из которых содержит данные поля таблицы, разделенные запятыми (или точками с запятой).  В джанго есть модуль csv, который предназначен для решения этой задачи. Пример ниже. Вроде все понятно - в первом приближении. Теперь уточняю задачу . Я должен сделать все также, как и  в твоем примере, только вместо PDF преобразовать в csv? Достаточно применить csv? Или воспользоваться чем-то другим - я нашел какие-то библиотеки.

import csv
from django.http import HttpResponse

def some_view(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'

```
writer = csv.writer(response)
writer.writerow(['First row', 'Foo', 'Bar', 'Baz'])
writer.writerow(['Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"])

return response
```

**Comment by p-p-m** [comment]
> Я должен сделать все также, как и в твоем примере, только вместо PDF преобразовать в csv?

да. Только идея в том чтобы csv документ совпадал с форматом html template. Т.е. чтобы если я изменю файл /templates/export/product_list.html, допустим добавлю туда колонку, то колонка добавится и в csv документ, который вы используете. В этом основная сложность.

> Достаточно применить csv?

да.

**Comment by awsh10** [comment]
для этого я должен каким-то образом анализировать этот шаблон и определять, какие поля должны входить?

**Comment by p-p-m** [comment]
да. Я бы сделал так: сначала отрендерил шаблон в строку: есть такой метод `render_to_string`. Потом бы распарсил строку с помощью `lxml` и записал данные в csv.

**Comment by awsh10** [comment]
Примерно ясно. Есть вопрос - имена колонок в таблице должны точно соответствовать именам полей в модели. Универсальный код вроде не получается - чтобы можно было применить для любого приложения с возможно различными названиями полей модели.

**Comment by p-p-m** [comment]
Для этого и создал шаблон. Я хочу менять шаблон и чтобы формат файла импорта менялся в зависимости от шаблона.

**Comment by awsh10** [comment]
Задачу вроде понимаю, а  вот метод решения нет. 
Есть шаблон. я должен выловить из него названия модели и полей. Для нашего случая это product.name and product.price. В других случаях это могут быть другие названия. Это я правильно понял?
Смотрел render_to_string. Но она же применяется для заполнения шаблона, как и все остальные функции render. Я не понял. как можно применить ее для определения требуемых полей.  Как по мне, этот шаблон нужно просто распарсить, определить поля и сформировать response/ Ежели что не так. подправляй
